### ISSUE TITLE
Motivation for Hagar

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [ReubenBond/Hagar#1]
This looks like a very cool project. 
I'm curious about what motivated you to build a new serialization library and format.

Was it as a learning experience?
Does it solve specific problems for a particular use case?

**Comment by ReubenBond** [comment]
The motivation is borne from experience with serialization in Orleans and elsewhere.
Specifically, see:
https://gist.github.com/ReubenBond/edffb6615e02a87ac22f00131290e2c2
https://github.com/dotnet/orleans/issues/2653
https://github.com/dotnet/orleans/issues/4554

Hope that answers your question.

The library certainly needs work before I would actively promote it - I haven't worked on the low level bit wrangling or buffer management at all, just took the easiest solution for me to get started with
