### ISSUE TITLE
Remove WireType.Fixed128 & leave as reserved

### ISSUE THREAD

**Issue by ReubenBond** [ReubenBond/Hagar#105]
This WireType is unnecessary and rarely used. I rather we keep it as reserved for the time being. This will mostly require rewriting the Guid codec to use a length prefix instead.

**Comment by mcm2020** [comment]
The Decimal Codec also uses Fixed128 -- should this be rewritten as well?

**Comment by mcm2020** [comment]
PR https://github.com/ReubenBond/Hagar/pull/106
