### ISSUE TITLE
UriCopier is tagged with [RegisterSerializer] instead of [RegisterCopier]

### ISSUE THREAD

**Issue by mcm2020** [ReubenBond/Hagar#186]
https://github.com/ReubenBond/Hagar/blob/8f0f106b2f3695874d5da744f8efeddf726c1275/src/Hagar/Codecs/UriCodec.cs#L40
https://github.com/ReubenBond/Hagar/blob/8f0f106b2f3695874d5da744f8efeddf726c1275/src/Hagar/Codecs/UriCodec.cs#L41

**Comment by ReubenBond** [comment]
Fixed
