### ISSUE TITLE
Codegen serializer skips complex get/set properties

### ISSUE THREAD

**Issue by Normanator** [ReubenBond/Hagar#192]
In attempting to change a property's type, we added a bridge-property that can take its value if an older client only sends the  original property.  This caused codegen to silently ignore the new property altogether (i.e. new client to new server case).

Repro:
```cs
   [Hagar.GenerateSerializer]
    public class Foo { 
      ...
        private string? versHack;

        // To change property RuleEnvironmentId from Guid to string, we add an Id(13) 
        // until world-wide rollout allows us to retire Id(12) and use just a normal auto-property on Id(13).
        [JsonIgnore]
        [Hagar.Id(12)]
        public Guid versHackRuleEnvironmentId { get; set; }

        [JsonPropertyName("ruleEnvironmentId")]
        [Hagar.Id(13)]
        public string RuleEnvironmentId
        {
            get => versHack ??= versHackRuleEnvironmentId.ToString();
            set
            {
                versHack = value;
                versHackRuleEnvironmentId = Guid.TryParse(value, out Guid g) ? g : default;
            }
        }
```

Expected: Write includes both 12 and 13 fields.
Actual: 
* Write only has Id(12) field.  
* No Hagar.Analyzer warning that Id(13) would be dropped by code-gen.  

Workaround: Write an IFieldCodec<Foo>.

**Comment by ReubenBond** [comment]
Thanks for investigating & reporting, @Normanator! I suppose we need to change the codegen logic.
