### ISSUE TITLE
Can't find Hagar package on Nuget.org

### ISSUE THREAD

**Issue by azhmur** [ReubenBond/Hagar#41]
I can't find published Hagar package on Nuget.org. Is some other repository used or I'm missing something?

**Comment by ReubenBond** [comment]
The package isn't on NuGet yet because I don't consider it ready for wider consumption.

`build.ps1` calls `dotnet build` and `dotnet pack` so you can create packages for local testing using that.

**Comment by azhmur** [comment]
Thank you.

PS Maybe you should mention it in readme.md.

**Comment by ReubenBond** [comment]
Sure thing, thanks
