### ISSUE TITLE
Is there some "Getting started" tutorial/example?

### ISSUE THREAD

**Issue by byme8** [ReubenBond/Hagar#42]
I am working on similar project(it isn't public yet) and would like to do some benchmarking, but failed to find any guilds how to install and use Hagar

**Comment by byme8** [comment]
sorry my bad, I have found sample directory in repo

**Comment by ReubenBond** [comment]
No worries, @byme8 😄 Feel free to message me if you have any questions.

I have not optimized much of the deserialization path yet, so there is likely more performance to be gained there.
