### ISSUE TITLE
future of Hagar

### ISSUE THREAD

**Issue by zvolkov** [ReubenBond/Hagar#58]
hello @ReubenBond is this project something you may consider developing further? I consult a US company whose serialization needs align very closely with your design philosophy here. They built a cumbersome set of extensions on top of protobuf which I would be happy to get rid of. Would you be interested in working together to iron out any remaining wrinkles in your library? Say I got permission for me to spend some serious time on this, would you be available to hand-hold?

**Comment by ReubenBond** [comment]
Hi @zvolkov, yes, I am interested in developing this further and productionizing it.
One of the main things remaining, is that I wanted to settle on a better way to serialize type names. I was considering porting the CLR type name parser + rewriter from this PR and using that to serialize types in a way that lets users add their own mapping (eg, for when they refactor their type names/namespaces/assemblies): https://github.com/dotnet/orleans/pull/6546/files

Other than that, I would like to add more tests, improve usability, and to optimize the deserialization path further.
I will be more available from next week onwards, certainly happy to help you to become familiar with the internals.

**Comment by zvolkov** [comment]
1. I tried hooking up the MsBuild generator by adding the nuget package to my project. Your Hagar.CodeGenerator.MSBuild missed dependency on Hagar.CodeGenerator.MsBuild.Tasks.csproj so the tasks dll wasn't included in the package. Once I added that, I stuck on the build failing with:

```
error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" "C:\dev\nuget\packages\hagar.codegenerator.msbuild\0.2.4-dev-20200730152938\build\..\tasks\netcoreapp3.0\Hagar.CodeGenerator.MSBuild.dll" "C:\dev\asd\.artifacts\binaries\obj\Core\Core.Common\Debug\netstandard2.1\Geico.AsdService.Core.Common.hagar.g.args.txt"" exited with code -1
```
I set HagarCodeGenLogLevel to Debug and I see generator getting to the last reference in hagar.g.args.txt and then saying:

```
dbug: Hagar.CodeGenerator[0]
        Project: Microsoft.CodeAnalysis.ProjectInfo
  info: Hagar.CodeGenerator[0]
        GetCompilation completed in 481ms.
  info: Hagar.CodeGenerator[0]
        Code generation completed in 1216ms
```

looks like it succeeded, not sure why I get that MSB3073.

Then I switched focus and started looking at your support of ISerializable. So all I need to do is register DotNetSerializableCodec? Do I still need to codegen-process my assemblies containing ISerializable types?

**Comment by zvolkov** [comment]
Oh so the codegen quits if the project it's processing does not reference Hagar assembly. Does this mean if I have a 100% ISerializable (no Hagar annotations) project I don't need to codegen it?

**Comment by zvolkov** [comment]
When you generate activators, you're trying to instantiate even abstract types (flagged as ISerializable), e.g.

```
    [System.CodeDom.Compiler.GeneratedCodeAttribute("HagarGen", "0.2.4.0")]
    internal sealed class HagarGen_Activator_ImmutableChangeCollection_F40B6<TImmutableChanges> : global::Hagar.Activators.IActivator<global::Some.NameSpace.ImmutableChangeCollection<TImmutableChanges>> where TImmutableChanges : class, new()
    {
        public global::Some.NameSpace.ImmutableChangeCollection<TImmutableChanges> Create() => new global::Some.NameSpace.ImmutableChangeCollection<TImmutableChanges>();
    }
```

I suppose these should be skipped? I will try and find where that happens.

**Comment by zvolkov** [comment]
Tried to port https://github.com/dotnet/orleans/issues/6073 - but hagar still tried to codegen during package-only builds. Had to add NoBuild condition to Hagar_CodeGeneratorEnabled:

```
<Hagar_CodeGeneratorEnabled Condition="'$(DesignTimeBuild)' != 'true' and '$(NoBuild)' != 'true'">true</Hagar_CodeGeneratorEnabled>
```

**Comment by zvolkov** [comment]
Alright, so I got to a point where I can run my serialization test suite through hagar. About half of the tests pass, which is pretty good. Many failures are due to Hagar.ReferenceNotFoundException, so I suppose I'm doing something wrong with sessions?

**Comment by zvolkov** [comment]
Getting CodecNotFoundException trying to serialize a generic [Serializable]/ISerializable. Basically, take your SimpleISerializableObject and make the Payload property be T instead of string.

**Comment by zvolkov** [comment]
Hm... I did not realize you did not support plain [Serializable] (without ISerializable). Is that intentional or am I confused?

I guess this would be a good point to stop and process all of the above, before I get too annoying.
Thank you sir, and I hope I wasn't too bothersome.

**Comment by ReubenBond** [comment]
Hi @zvolkov, not bothersome at all. I have just been busy with .NET Conf and other things.

Ideally, we would port the code generator to use the new .NET Source Generators feature for C# 9, which would require that users upgrade to the new SDK once it's available (but do not need to change runtime versions).

There is a test that shows how to use ISerializable (reminds me that there are zero docs).

[Serializable] is not the same as ISerializable. Hagar uses a different attribute to decide if it should generate a serializer for your class. You don't need to generate serializers for ISerializable classes, since they will use that interface instead (and therefore will serialize using that different format, which is more key-value based and less performant). That mode is intended for cases where you can't change the class. I need to have a strategy for surrogate serialization for cases where you want an efficient/fast representation of the class but also cannot modify it or access its internals.

Serialization with Hagar is supposed to involve adding attributes to properties/fields on your class which are serialized. That is how it supports schema changes (version tolerance): by making the user explicitly identify their fields, numerically.

**Comment by zvolkov** [comment]
Understood. Yeah, [Serializable] classes with lots of polymorphism (interfaces, abstract classes, and generics upon generics) are my prime use-cases. Plus some simple un-annotated types here and there.

**Comment by ReubenBond** [comment]
Are you able to modify the classes to add the (currently required) `[Id(x)]` attributes in your case?

**Comment by zvolkov** [comment]
Not at my scale, no. It's a large "enterprise" system with way too many classes to annotate. Some of them are generated from web service schema etc. My sole interest in Hagar came from your work on Orleans where it looked like it was meant to serialize arbitrary DTOs originally meant for BinaryFormatter. Honestly, version tolerance is of the secondary interest to me because a large enterprise system will inevitably have other issues getting in the way of in-place deployments and is more likely to evolve in the direction of blue/green anyway. For our purposes it would be sufficient if it matched the fields (of the serialized image and the target type) pairwise by type, and upon encountering a mismatched type attempted to skip and recover. Sort of like what the text diffing does to align two chunks of text, but based on the field types.

I'm beginning to realize you were actually aiming at a different usage pattern with your design, so I'm a bit sad there is a disconnect there. I don't think you were aiming for this to be a generic BinaryFormatter replacement and yet that is what I need, especially given the current situation with serializers in .net ecosystem. 

Anyway, I'm still interested and cautiously optimistic we can find a way forward with this.

**Comment by ReubenBond** [comment]
This is certainly not intended to be a drop-in BinaryFormatter replacement (which has security and performance issues, by the way).

This is intended to be free of magic, only serializing types that you specify. The ISerializable support in Hagar does allow for similar behavior to BinaryFormatter for any ISerializable type (can allow/block types), but it wont serialize any arbitrary type marked `[Serializable]`.

For that use case, I believe [Hyperion](https://github.com/akkadotnet/Hyperion) probably fits your needs, especially if version tolerance is not a requirement.

**Comment by ReubenBond** [comment]
I think we can close this. The project is evolving rapidly :)

**Comment by zvolkov** [comment]
Agreed. Hyperion is not looking healthy to me but this issue can be closed. I'll wait until a contender for a replacement of BinaryFormatter arises.
